# Generated by Django 4.1.3 on 2023-01-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='bts',
            name='integrantes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coreasur',
            name='soft_power',
            field=models.CharField(max_length=200),
        ),
    ]
