# Generated by Django 4.1.3 on 2023-01-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbts', '0003_bts_edadcoreana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bts',
            name='edadcoreana',
            field=models.IntegerField(default=0),
        ),
    ]
