# Generated by Django 4.1.3 on 2023-01-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbts', '0004_alter_bts_edadcoreana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bts',
            name='edadcoreana',
            field=models.IntegerField(),
        ),
    ]
