# Generated by Django 4.1.3 on 2023-01-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbts', '0005_alter_bts_edadcoreana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bts',
            name='edadcoreana',
            field=models.IntegerField(verbose_name=str),
        ),
    ]
