# Generated by Django 4.1.3 on 2023-01-08 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbts', '0006_alter_bts_edadcoreana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bts',
            name='edadcoreana',
        ),
    ]
