# Generated by Django 4.1.3 on 2023-01-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbts', '0007_remove_bts_edadcoreana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='army',
            old_name='resumen',
            new_name='fundadoras',
        ),
    ]
