# Generated by Django 4.1.3 on 2023-01-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbts', '0008_rename_resumen_army_fundadoras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='army',
            old_name='fundadoras',
            new_name='resumen',
        ),
    ]
